### PR TITLE
Upload on the master branch of the CF feedstock only

### PR DESCRIPTION
**Pull request by mrakitin**
This is what @CJ-Wright mentioned in https://github.com/conda-forge/ophyd-feedstock/pull/18#issuecomment-599154973. After this configuration is in, the PRs here can be made from the branches of this feedstock. See https://conda-forge.org/docs/maintainer/conda_forge_yml.html#upload-on-branch for more details.

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Comment by mrakitin** [comment]
This change actually adds @zllentz to the list of codeowners/maintainers. The feedstock has to be always rerendered once a new maintainer is added.

**Comment by mrakitin** [comment]
@klauer, @hhslepicka, do you mind to check it and merge?

**Comment by mrakitin** [comment]
Thanks Hugo! The green button is waiting for you ;o)

**Comment by hhslepicka** [comment]
Let it fly! ✅

**Comment by mrakitin** [comment]
Cool, thanks @hhslepicka!

**Pull request merged**
