### PR TITLE
Support windows?

### PR DESCRIPTION
**Pull request by CJ-Wright**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge-admin please rerender

**Comment by CJ-Wright** [comment]
@conda-forge/core the webservice seems unhappy?

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

(It was redeployed recently.)

**Comment by CJ-Wright** [comment]
@conda-forge/event-model can this get a merge?

**Comment by mrakitin** [comment]
I'd be happy to merge, but don't seem to have merge rights, although I am in the @conda-forge/event-model team. Is there anything wrong with the membership?

**Comment by CJ-Wright** [comment]
Interesting. I'm going to fix this now, but also raise it as a bug.

**Comment by jakirkham** [comment]
AFAICT the team permissions are working correctly. Not sure why you don't have permissions here.

Screen Shot 2019-06-17 at 11 05 19 PM

**Comment by mrakitin** [comment]
Thanks all for your help, now I have the green button to merge it! @CJ-Wright, what was the fix?

**Comment by CJ-Wright** [comment]
We just removed the skip I'm not certain why it was there in the first place.

**Pull request merged**
