### PR TITLE
Add zllentz as a maintainer

### PR DESCRIPTION
**Pull request by klauer**
Let's _keep it maintained_ ❗️ ❗️ 

@zllentz please confirm you're willing and able.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
You need to use PRs starting from your fork

**Comment by tacaswell** [comment]
> You need to use PRs starting from your fork

protocol wise or "it won't work" technical wise?

**Comment by CJ-Wright** [comment]
Unless special changes are made (:wave: @mrakitin) all branches on the feedstock build the package and push to anaconda.org. So this pr most likely meant that the package changes went into production already. (note that I think you still need to merge it for CF's other infrastructure, like changing the maintenance team to kick in) It is good practice to make the PR from a fork to avoid pushing up potentially broken packages.

**Comment by tacaswell** [comment]
So it _extra_ worked ;)

**Comment by klauer** [comment]
I think your information may be outdated, @CJ-Wright, or I'm misunderstanding. Grabbing the latest archive from https://anaconda.org/conda-forge/ophyd/files lists the following:

```
    recipe-maintainers:
        - conda-forge/event-model
        - danielballan
        - hhslepicka
        - klauer
        - mrakitin
        - tacaswell
```

And the archive went up prior to this PR: `2 days and 23 hours ago`.

**Comment by CJ-Wright** [comment]
Because you didn't change the version or build number. We don't upload packages that have the same version and build number as one that exists. However, it is good practice to make PRs from forks. https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests

**Comment by klauer** [comment]
So what you're saying is that your message doesn't apply to this specific PR but in all other scenarios we should be doing things from our own fork? Well understood.

The maintainer addition was a simple GitHub GUI edit which didn't require as much effort as forking. I apologize for all of the spam that this has generated. 

Back on topic, if the next person that could reply would be @zllentz I would appreciate it.

**Comment by ZLLentz** [comment]
I'm willing and able to help maintain this

**Pull request merged**
