### PR TITLE
del @cj-wright

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Comment by tacaswell** [comment]
It looks like azure does not want to let you go @CJ-Wright !

@conda-forge-admin, please rerender.

**Comment by CJ-Wright** [comment]
The errors are due to a SHA mismatch

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Pull request merged**
