### PR TITLE
Add 'inflection' dependency

### PR DESCRIPTION
**Pull request by dmgav**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrakitin** [comment]
This was discussed in https://github.com/conda-forge/ophyd-feedstock/pull/31, and people agreed it would make sense to not include `inflection` as it's not used in the main code (only used by a script that is not packaged for PyPI).

+1 for the `pip check`.

**Comment by dmgav** [comment]
`pip check` does not pass in other packages if they have ophyd as dependency. It will probably not pass here if I remove `inflection`.

**Comment by ZLLentz** [comment]
Just a quick note that, while I don't think a non-dependency should be a dependency, there are some code paths that throw errors if you defy the requirements stated in the setup.py file. I ran into one of these yesterday. I didn't know about these previously when I argued for not having an inflection dependency.

**Comment by mrakitin** [comment]
Thanks for the extra details, @ZLLentz! We are going to fix it via https://github.com/bluesky/ophyd/pull/1014. Please review if you have time (just a 2-line PR).

**Pull request closed without merging**
